operator:
  image: mirrord-operator
  sqsSplitting: true
  rmqSplitting: true
  kafkaSplitting: true
  mysqlBranching: true
  pgBranching: true
  mongodbBranching: true
  mssqlBranching: true
  previewEnv: true
  preview:
    image_pull_policy: "IfNotPresent"
  awsRoleArn: arn:aws:iam::000000000000:role/dummy
  metrics: true
  jsonLog: true
  logLevel: "mirrord=info,operator=info"
  otelTraceExportUrl: "http://tempo.observability.svc.cluster.local:4318"
  otelLogLevel: "operator=debug"
  injectSessionKeyHeader: true
  limits:
    memory: 512Mi
    cpu: 500m
  extraEnv:
    AWS_ENDPOINT_URL: "http://localstack.localstack.svc.cluster.local:4566"
    AWS_ACCESS_KEY_ID: "test"
    AWS_SECRET_ACCESS_KEY: "test"
    AWS_REGION: "us-east-1"
  # pgBranchConfig:
  #   dbPod:
  #     image:
  #       registry: "pgvector/pgvector"
  #     initImage:
  #       registry: "pgvector/pgvector"
  #     annotations:
  #       sidecar.istio.io/inject: "false"

disableTelemetries: true

agent:
  image: test
  extraConfig:
    log_level: "warn,mirrord=debug"
    network_interface: lo
    passthrough_mirroring: true
    image_pull_policy: "Never"

license:
  pemRef: "mirrord-operator-license-pem"
  allowSeatOverages: false
createNamespace: false
image:
  pullPolicy: Never
