apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: redis-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis-app
          image: redis-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDR
              value: "redis-main:6379"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
  namespace: redis-test
spec:
  selector:
    app: redis-app
  ports:
    - port: 8080
      targetPort: 8080

