version: '3'

vars:
  BINARY_NAME: test-cli
  BUILD_DIR: ../../bin

tasks:
  build:
    desc: "Build the test CLI"
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} .
      - echo "Built {{.BUILD_DIR}}/{{.BINARY_NAME}}"

  deps:
    desc: "Download and tidy Go dependencies"
    cmds:
      - go mod download
      - go mod tidy

  clean:
    desc: "Remove built binary"
    cmds:
      - rm -f {{.BUILD_DIR}}/{{.BINARY_NAME}}

  test:
    desc: "Run tests"
    cmds:
      - go test -v ./...

  fmt:
    desc: "Format Go code"
    cmds:
      - go fmt ./...

  vet:
    desc: "Run go vet"
    cmds:
      - go vet ./...

  check:
    desc: "Run all checks (fmt, vet, test)"
    deps: [fmt, vet, test]

