apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-mirrord

resources:
  - ../kafka

patches:
  - target:
      group: queues.mirrord.metalbear.co
      version: v1alpha
      kind: MirrordKafkaTopicsConsumer
      name: kafka-consumer
      namespace: test-mirrord
    patch: |
      - op: add
        path: /spec/splitTtl
        value: 30
