apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: MongodbBranchDatabase CRDs are created dynamically by mirrord during a session.
# They are ephemeral and get deleted when the session ends.
resources:
  - secret.yaml
  - pod.yaml
# - branch.yaml  # Branches are created by mirrord, not deployed manually
