apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: test-mirrord
type: Opaque
stringData:
  DATABASE_URL: "mongodb://admin:password@mongodb-test.test-mirrord.svc.cluster.local:27017/source_db?authSource=admin"
