apiVersion: queues.mirrord.metalbear.co/v1
kind: MirrordSplitConfig
metadata:
  name: confluent-consumer
  namespace: test-mirrord
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: confluent-consumer
  queues:
    - id: test-topic
      kind: kafka
      clientConfig: confluent-kafka-connection
      appConfig:
        topic:
          - env: KAFKA_TOPIC_NAME
        groupId:
          - env: KAFKA_GROUP_ID
