apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../sqs-localstack
  - service-account.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sqs-consumer
        namespace: test-mirrord
      spec:
        template:
          spec:
            serviceAccountName: test-sa

