apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
  namespace: test-mirrord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqs-consumer
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      containers:
      - name: consumer
        image: sqs-consumer:local
        imagePullPolicy: Never

