# Operator values for PRIMARY cluster - 2 CLUSTERS (primary + 1 remote)
operator:
  image: mirrord-operator
  sqsSplitting: true
  kafkaSplitting: true
  mysqlBranching: true
  pgBranching: true
  awsRoleArn: arn:aws:iam::000000000000:role/dummy
  metrics: true 
  jsonLog: true
  logLevel: "debug"
  multiCluster:
    enabled: true
    remoteSessionTimeoutSecs: 60
  extraEnv:
    MIRRORD_MULTI_CLUSTER_ENABLED: "true"
    MIRRORD_IS_PRIMARY_CLUSTER: "true"
    MIRRORD_PRIMARY_CLUSTER: "primary"
    # When PRIMARY_MANAGEMENT_ONLY=true, default cluster must be non management cluster
    MIRRORD_DEFAULT_CLUSTER: "primary"
    MIRRORD_MULTI_CLUSTER_CONTEXTS: '{"primary":"mirrord-primary","remote-1":"mirrord-remote-1"}'
    PRIMARY_MANAGEMENT_ONLY: "false"
license:
  pemRef: "mirrord-operator-license-pem"
createNamespace: false
image:
  pullPolicy: Never
