apiVersion: queues.mirrord.metalbear.co/v1
kind: MirrordSplitConfig
metadata:
  name: temporal-test-config
  namespace: test-mirrord
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temporal-worker
  clientConfigs:
    temporal: temporal-connection
  queues:
  - id: order-checkout
    kind: temporal
    appConfig:
      taskQueue:
      - env: TEMPORAL_TASK_QUEUE
      temporalAddress:
      - env: TEMPORAL_ADDRESS
      temporalNamespace:
      - env: TEMPORAL_NAMESPACE
