apiVersion: queues.mirrord.metalbear.co/v1
kind: MirrordSplitConfig
metadata:
  name: nats-test-config
  namespace: test-mirrord
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nats-consumer
  clientConfigs:
    nats: nats-sandbox-config
  queues:
  - id: orders
    kind: nats
    appConfig:
      stream:
      - env: NATS_STREAM
      consumer:
      - env: NATS_CONSUMER
