apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-mirrord

resources:
  - ../kafka-statefulset

patches:
  - target:
      kind: StatefulSet
      name: kafka-consumer
    patch: |
      - op: add
        path: /spec/updateStrategy
        value:
          type: OnDelete
