apiVersion: dbs.mirrord.metalbear.co/v1alpha1
kind: BranchDatabase
metadata:
  name: mssql-test-branch-env-val
spec:
  id: mssql-test-env-val-branch
  target:
    apiVersion: v1
    kind: Pod
    name: mssql-server-env-val
    container: echo
  connectionSource:
    url:
      env:
        variable: DATABASE_URL
        container: echo
  databaseName: source_db
  version: "2022-latest"
  ttlSecs: 600
  mssqlOptions:
    copy:
      mode: all
