apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kafka
  - service-account.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kafka-consumer
        namespace: test-mirrord
      spec:
        template:
          spec:
            serviceAccountName: kafka-test-sa

