apiVersion: queues.mirrord.metalbear.co/v1
kind: MirrordSplitConfig
metadata:
  name: servicebus-topic-test-config
  namespace: test-mirrord
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicebus-topic-consumer
  clientConfigs:
    azureServiceBus: servicebus-emulator-config
  queues:
  - id: test-topic-sub
    kind: azureServiceBus
    appConfig:
      topic:
      - env: SERVICEBUS_TOPIC_NAME
      subscription:
      - env: SERVICEBUS_SUBSCRIPTION_NAME
