#!/usr/bin/env bash
# One-stop runner for crm-server's Postgres-backed tests, built around the
# stale-connection fix (GET /api/v1/ci/sessions returned 500 when a pooled DB
# connection died between the pool's ping and the query).
#
# What it does:
#   1. checks docker, cargo and the ../operator checkout
#   2. starts (or reuses) the throwaway Postgres container the tests expect
#   3. runs `cargo test -p crm-server sql_models::ci -- --include-ignored`
#      or, in before/after mode, first runs the regression tests on the pre-fix
#      code (a git worktree at BEFORE_REF plus the test-only patch next to this
#      script) to show the original failure, then the current tree with the fix
#
# Uses charmbracelet/gum for the UI when installed (brew install gum) and falls
# back to plain output otherwise.
#
# Usage:
#   scripts/crm-db-tests.sh                 # interactive menu
#   scripts/crm-db-tests.sh after           # run the tests with the fix
#   scripts/crm-db-tests.sh before-after    # reproduce the 500, then verify the fix
#   scripts/crm-db-tests.sh db              # only make sure Postgres is up
#   scripts/crm-db-tests.sh clean           # remove the Postgres container
#
# Env: PG_CONTAINER (ci-sessions-test-pg), PG_PORT (55432), OPERATOR_DIR (../operator),
#      BEFORE_REF (default: the parent of the commit that introduced the retry helper)
#
# The test-only patch is the tests module of ci.rs without the fix; it applies to
# the pre-fix commit on vladr/INT-720 and was generated by diffing that commit's
# ci.rs against the same file with only the test additions.
set -uo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OPERATOR_DIR="${OPERATOR_DIR:-$ROOT_DIR/../operator}"
PG_CONTAINER="${PG_CONTAINER:-ci-sessions-test-pg}"
PG_PORT="${PG_PORT:-55432}"
PG_IMAGE="postgres:16-alpine"
CI_RS="$OPERATOR_DIR/services/crm-server/src/sql_models/ci.rs"
TEST_PATCH="$ROOT_DIR/scripts/crm-stale-connection-test-only.patch"
LOG_DIR="$(mktemp -d /tmp/crm-db-tests.XXXXXX)" || { echo "mktemp failed"; exit 1; }
MODE="${1:-}"

HAS_GUM=0
command -v gum >/dev/null 2>&1 && HAS_GUM=1

# ── UI helpers (gum when available, plain fallback) ───────────────────────────

title() {
  if ((HAS_GUM)); then
    gum style --border double --padding "0 2" --margin "1 0" --border-foreground 212 "$@"
  else
    printf '\n== %s ==\n' "$*"
  fi
}
step() { if ((HAS_GUM)); then gum style --foreground 212 --bold "▸ $*"; else printf '\n▸ %s\n' "$*"; fi; }
ok()   { if ((HAS_GUM)); then gum style --foreground 42 "  ✔ $*"; else printf '  ✔ %s\n' "$*"; fi; }
warn() { if ((HAS_GUM)); then gum style --foreground 214 "  ! $*"; else printf '  ! %s\n' "$*"; fi; }
die()  { if ((HAS_GUM)); then gum style --foreground 196 "  ✘ $*"; else printf '  ✘ %s\n' "$*"; fi; exit 1; }
spin() { # message command...
  local msg=$1; shift
  if ((HAS_GUM)); then gum spin --spinner dot --title "$msg" -- "$@"; else echo "  $msg"; "$@"; fi
}

# ── preflight ─────────────────────────────────────────────────────────────────

preflight() {
  step "Preflight"
  command -v docker >/dev/null 2>&1 || die "docker CLI not found"
  docker info >/dev/null 2>&1 || die "docker daemon is not running (start Docker Desktop or colima)"
  ok "docker is up"
  command -v cargo >/dev/null 2>&1 || die "cargo not found"
  ok "cargo: $(cargo --version)"
  [ -f "$CI_RS" ] || die "operator checkout not found at $OPERATOR_DIR (set OPERATOR_DIR)"
  ok "operator checkout: $OPERATOR_DIR"
  ((HAS_GUM)) || warn "gum not installed - plain output (brew install gum)"
}

# ── postgres container ────────────────────────────────────────────────────────

wait_ready() {
  local i
  for i in $(seq 1 30); do
    docker exec "$PG_CONTAINER" pg_isready -U postgres -q >/dev/null 2>&1 && return 0
    sleep 1
  done
  return 1
}
export -f wait_ready
export PG_CONTAINER

ensure_postgres() {
  step "Postgres container $PG_CONTAINER"
  # docker inspect prints a blank line before failing on a missing container, so ask
  # for existence first and only then for the state.
  local state=missing
  if docker inspect "$PG_CONTAINER" >/dev/null 2>&1; then
    state=$(docker inspect -f '{{.State.Status}}' "$PG_CONTAINER")
  fi
  case "$state" in
    running)
      ok "already running" ;;
    missing)
      spin "creating $PG_CONTAINER from $PG_IMAGE on port $PG_PORT" \
        docker run -d --name "$PG_CONTAINER" -e POSTGRES_PASSWORD=postgres -p "$PG_PORT:5432" "$PG_IMAGE" \
        >/dev/null || die "docker run failed (is port $PG_PORT free?)"
      ok "created" ;;
    *)
      spin "starting stopped container (was: $state)" docker start "$PG_CONTAINER" >/dev/null \
        || die "docker start failed - inspect with: docker logs $PG_CONTAINER"
      ok "started" ;;
  esac

  # An existing container keeps the port it was created with, so trust docker over PG_PORT.
  local bound_port
  bound_port=$(docker port "$PG_CONTAINER" 5432/tcp 2>/dev/null | head -1 | awk -F: '{print $NF}')
  if [ -n "$bound_port" ] && [ "$bound_port" != "$PG_PORT" ]; then
    warn "container listens on $bound_port, not PG_PORT=$PG_PORT - using $bound_port"
    PG_PORT=$bound_port
  fi
  DATABASE_URL="postgres://postgres:postgres@localhost:$PG_PORT/postgres"

  spin "waiting for postgres to accept connections" bash -c wait_ready \
    || die "postgres not ready after 30s - check: docker logs $PG_CONTAINER"
  ok "ready at $DATABASE_URL"
}

remove_postgres() {
  step "Removing $PG_CONTAINER"
  if docker inspect "$PG_CONTAINER" >/dev/null 2>&1; then
    docker rm -f "$PG_CONTAINER" >/dev/null && ok "removed"
  else
    ok "nothing to remove"
  fi
}

# ── tests ─────────────────────────────────────────────────────────────────────

run_tests() { # label checkout-dir
  local log="$LOG_DIR/$1.log"
  step "cargo test ($1, $2) - streaming, copy in $log"
  # One target dir for both checkouts, so the pre-fix build reuses every dependency.
  (
    cd "$2" &&
      CARGO_TARGET_DIR="$OPERATOR_DIR/target" SQLX_OFFLINE=true DATABASE_URL="$DATABASE_URL" \
        cargo test -p crm-server sql_models::ci -- --include-ignored --nocapture
  ) 2>&1 | tee "$log"
  return "${PIPESTATUS[0]}"
}

WORKTREE=""
remove_worktree() {
  [ -n "$WORKTREE" ] || return 0
  git -C "$OPERATOR_DIR" worktree remove --force "$WORKTREE" >/dev/null 2>&1 && ok "pre-fix worktree removed" \
    || warn "could not remove worktree $WORKTREE - run: git -C $OPERATOR_DIR worktree prune"
  WORKTREE=""
}

# The commit right before the fix: parent of the first commit that added the retry helper.
default_before_ref() {
  local fix_commit
  fix_commit=$(git -C "$OPERATOR_DIR" log --format=%H --reverse -S'fn retry_on_stale_connection' \
    -- services/crm-server/src/sql_models/ci.rs | head -1)
  [ -n "$fix_commit" ] && echo "${fix_commit}^"
}

before_after() {
  local ref
  ref=$(git -C "$OPERATOR_DIR" rev-parse --verify "${BEFORE_REF:-$(default_before_ref)}" 2>/dev/null) \
    || die "could not resolve the pre-fix commit - set BEFORE_REF to the commit right before the fix"
  [ -f "$TEST_PATCH" ] || die "test-only patch missing: $TEST_PATCH"

  step "Pre-fix code: git worktree at ${ref:0:12} plus the regression tests only"
  WORKTREE="$LOG_DIR/before-worktree"
  git -C "$OPERATOR_DIR" worktree add --detach "$WORKTREE" "$ref" >/dev/null 2>&1 \
    || { WORKTREE=""; die "git worktree add failed for $ref - set BEFORE_REF to a commit without the fix"; }
  trap remove_worktree EXIT
  git -C "$WORKTREE" apply "$TEST_PATCH" \
    || die "the test-only patch does not apply on ${ref:0:12} - set BEFORE_REF to the commit right before the fix, or regenerate the patch"
  ok "worktree has the tests and none of the fix"

  run_tests before "$WORKTREE"; local before_rc=$?
  remove_worktree; trap - EXIT
  run_tests after "$OPERATOR_DIR"; local after_rc=$?

  local before_verdict after_verdict
  if [ "$before_rc" -ne 0 ] && grep -q "got 0 bytes at EOF" "$LOG_DIR/before.log"; then
    before_verdict="REPRODUCED - request failed with 'expected to read 5 bytes, got 0 bytes at EOF'"
  elif [ "$before_rc" -ne 0 ]; then
    before_verdict="FAILED, but not with the EOF error - read $LOG_DIR/before.log"
  else
    before_verdict="UNEXPECTED PASS - the stale path was not hit, read $LOG_DIR/before.log"
  fi
  if [ "$after_rc" -eq 0 ]; then
    after_verdict="FIXED - the retry answered from a connection opened after the cut"
  else
    after_verdict="STILL FAILING - read $LOG_DIR/after.log"
  fi

  title "BEFORE / AFTER" \
    "before (${ref:0:12}, no retry): $before_verdict" \
    "after  (current tree):        $after_verdict"
  [ "$before_rc" -ne 0 ] && [ "$after_rc" -eq 0 ]
}

next_steps() {
  printf '\nNext:\n'
  printf '  task crm:db-tests                rerun the suite\n'
  printf '  task crm:db-tests:before-after   reproduce the 500, then verify the fix\n'
  printf '  task crm:pg:down                 remove the Postgres container\n'
  printf '  logs: %s\n' "$LOG_DIR"
}

# ── main ──────────────────────────────────────────────────────────────────────

title "crm-server DB tests" "stale pooled connection -> GET /api/v1/ci/sessions 500"

if [ -z "$MODE" ]; then
  if ((HAS_GUM)); then
    choice=$(gum choose --header "What do you want to do?" \
      "after: run the crm-server DB tests with the fix" \
      "before-after: reproduce the 500, then verify the fix" \
      "db: only make sure Postgres is up" \
      "clean: remove the Postgres container" </dev/tty) || exit 0
    MODE=${choice%%:*}
  else
    MODE=after
  fi
fi

case "$MODE" in
  clean)
    preflight; remove_postgres ;;
  db)
    preflight; ensure_postgres; next_steps ;;
  after)
    preflight; ensure_postgres
    run_tests after "$OPERATOR_DIR"; rc=$?
    if [ "$rc" -eq 0 ]; then ok "all sql_models::ci tests passed"; else die "tests failed (exit $rc) - see $LOG_DIR/after.log"; fi
    next_steps ;;
  before-after)
    preflight; ensure_postgres
    before_after || { next_steps; exit 1; }
    next_steps ;;
  *)
    die "unknown mode '$MODE' (after | before-after | db | clean)" ;;
esac
