apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../sqs
  - localstack-namespace.yaml
  - localstack.yaml

configMapGenerator:
  - name: localstack-init
    namespace: localstack
    options:
      disableNameSuffixHash: true
    files:
      - init.sh

patches:
  - target:
      kind: Deployment
      name: sqs-consumer
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sqs-consumer
        namespace: test-mirrord
      spec:
        template:
          spec:
            # Wait for LocalStack to be ready before starting the consumer
            initContainers:
            - name: wait-for-localstack
              image: busybox:latest
              command:
              - sh
              - -c
              - |
                echo "Waiting for LocalStack to be ready..."
                until wget -q --spider http://localstack.localstack.svc.cluster.local:4566/_localstack/health 2>/dev/null; do
                  echo "LocalStack not ready yet, retrying in 2s..."
                  sleep 2
                done
                echo "LocalStack is ready!"
            containers:
            - name: consumer
              env:
              - name: QUEUE_NAME
                value: "TestQueue"
              - name: AWS_ENDPOINT_URL
                value: "http://localstack.localstack.svc.cluster.local:4566"
              - name: AWS_ACCESS_KEY_ID
                value: "test"
              - name: AWS_SECRET_ACCESS_KEY
                value: "test"
              - name: AWS_DEFAULT_REGION
                value: "eu-north-1"
              - name: AWS_REGION
                value: "eu-north-1"

