apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        env:
        - name: SERVICES
          value: "sqs"
        - name: AWS_DEFAULT_REGION
          value: "eu-north-1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_REGION
          value: "eu-north-1"
        ports:
        - containerPort: 4566
          name: edge
        volumeMounts:
        - name: init-scripts
          mountPath: /etc/localstack/init/ready.d
        readinessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: init-scripts
        configMap:
          name: localstack-init
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
spec:
  selector:
    app.kubernetes.io/name: localstack
  ports:
  - port: 4566
    targetPort: 4566
    name: edge

