apiVersion: mirrord.metalbear.co/v1
kind: MirrordPropertyList
metadata:
  name: bullmq-config
  namespace: test-mirrord
spec:
  properties:
  - name: url
    value: "redis://redis-main.redis-test.svc.cluster.local:6379"
